openapi: '3.0.1'
info:
  title: Directus API Reference
  description: This is a dynamically generated API specification for all endpoints existing on the current project!
  version: '11.1.0'
  license:
    name: Business Source License 1.1 (BUSL-1.1)
    url: https://github.com/directus/directus/blob/main/license
servers:
  - url: https://example.directus.app
    description: Your current Directus project.

paths:
  "/activity":
    $ref: paths/permissions/index.yaml
  "/activity/{id}":
    $ref: paths/permissions/_id/index.yaml
  "/activity/comment":
    $ref: paths/permissions/comment/index.yaml
  "/activity/comment/{id}":
    $ref: paths/permissions/comment/_id/index.yaml
  "/assets/{_id}":
    $ref: paths/assets/_id/index.yaml
  "/auth/login":
    $ref: paths/auth/login/index.yaml
  "/auth/logout":
    $ref: paths/auth/logout/index.yaml
  "/auth/oauth":
    $ref: paths/auth/oauth/index.yaml
  "/auth/oauth/{_provider}":
    $ref: paths/auth/oauth/_provider/index.yaml
  "/auth/password/request":
    $ref: paths/auth/password/request/index.yaml
  "/auth/password/reset":
    $ref: paths/auth/password/reset/index.yaml
  "/auth/refresh":
    $ref: paths/auth/refresh/index.yaml
  "/collections":
    $ref: paths/collections/index.yaml
  "/collections/{_id}":
    $ref: paths/collections/_id/index.yaml
  "/extensions":
    $ref: paths/extensions/index.yaml
  "/extensions/{_bundle}/{_name}":
    $ref: paths/extensions/_bundle/_name/index.yaml
  "/extensions/{_name}":
    $ref: paths/extensions/_name/index.yaml
  "/fields":
    $ref: paths/fields/index.yaml
  "/fields/{_collection}":
    $ref: paths/fields/_collection/index.yaml
  "/fields/{_collection}/{_id}":
    $ref: paths/fields/_collection/_id/index.yaml
  "/files":
    $ref: paths/files/index.yaml
  "/files/{_id}":
    $ref: paths/files/_id/index.yaml
  "/flows":
    $ref: paths/flows/index.yaml
  "/flows/{_id}":
    $ref: paths/flows/_id/index.yaml
  "/folders":
    $ref: paths/folders/index.yaml
  "/folders/{_id}":
    $ref: paths/folders/_id/index.yaml
  "/operations":
    $ref: paths/operations/index.yaml
  "/operations/{_id}":
    $ref: paths/operations/_id/index.yaml
  "/permissions":
    $ref: paths/permissions/index.yaml
  "/permissions/{id}":
    $ref: paths/permissions/_id/index.yaml
  "/permissions/me":
    $ref: paths/permissions/me/index.yaml
  "/presets":
    $ref: paths/presets/index.yaml
  "/presets/{id}":
    $ref: paths/presets/_id/index.yaml
  "/relations":
    $ref: paths/relations/index.yaml
  "/relations/{id}":
    $ref: paths/relations/_id/index.yaml
  "/revisions":
    $ref: paths/revisions/index.yaml
  "/revisions/{id}":
    $ref: paths/revisions/_id/index.yaml
  "/roles":
    $ref: paths/roles/index.yaml
  "/roles/{id}":
    $ref: paths/roles/_id/index.yaml
  "/schema/apply":
    $ref: paths/schema/apply/index.yaml
  "/schema/diff":
    $ref: paths/schema/diff/index.yaml
  "/schema/snapshot":
    $ref: paths/schema/snapshot/index.yaml
  "/server/info":
    $ref: paths/server/info/index.yaml
  "/server/ping":
    $ref: paths/server/ping/index.yaml
  "/settings":
    $ref: paths/settings/index.yaml
  "/users":
    $ref: paths/users/index.yaml
  "/users/{id}":
    $ref: paths/users/_id/index.yaml
  "/users/invite":
    $ref: paths/users/invite/index.yaml
  "/users/invite/accept":
    $ref: paths/users/invite/accept/index.yaml
  "/users/me":
    $ref: paths/users/me/index.yaml
  "/users/me/tfa":
    $ref: paths/users/me/tfa/index.yaml
  "/users/me/tfa/disable":
    $ref: paths/users/me/tfa/disable/index.yaml
  "/users/me/tfa/enable":
    $ref: paths/users/me/tfa/enable/index.yaml
  "/users/me/track/page":
    $ref: paths/users/me/track/page/index.yaml
  "/utils/cache/clear"
    $ref: paths/utils/cache/clear/index.yaml
  "/utils/export/{_collection}"
    $ref: paths/utils/export/_collection/index.yaml
  "/utils/hash"
    $ref: paths/utils/hash/index.yaml
  "/utils/import/{_collection}"
    $ref: paths/utils/import/_collection/index.yaml
  "/utils/random/string"
    $ref: paths/utils/random/string/index.yaml
  "/utils/sort/{_collection}"
    $ref: paths/utils/sort/_collection/index.yaml
  "/versions":
    $ref: paths/versions/index.yaml
  "/versions/{id}":
    $ref: paths/versions/id/index.yaml
  "/versions/{id}/compare":
    $ref: paths/versions/id/compare/index.yaml
  "/versions/{id}/promote":
    $ref: paths/versions/id/promote/index.yaml
  "/versions/{id}/save":
    $ref: paths/versions/id/save/index.yaml
  "/webhooks/":
    $ref: paths/webhooks/index.yaml
  "/webhooks/{id}":
    $ref: paths/webhooks/_id/index.yaml
components:
  parameters:
    $ref: components/parameters.yaml
  responses:
    $ref: components/responses.yaml
  securitySchemes:
    $ref: components/security.yaml
  schemas:
    $ref: components/schemas/_index.yaml
tags:
  - name: Assets
    description: Image typed files can be dynamically resized and transformed to fit any need.
  - name: Authentication
    description: All data within the platform is private by default. The public role can be configured to expose data without authentication, or you can pass an access token to the API to access private data.
  - name: Schema
    description: Retrieve and update the schema of an instance.
    x-authentication: admin
    x-schemas:
      - Schema
      - Diff
  - name: Server
    description: Access to where Directus runs. Allows you to make sure your server has everything needed to run the platform, and check what kind of latency we're dealing with.
  - name: Utilities
    description: Directus comes with various utility endpoints you can use to simplify your development flow.
    x-authentication: user
    x-schemas:
      - Files
      - Folders
      - Users
      - Roles
  - name: Folders
    description: Group files by virtual folders.
    x-collection: directus_folders
  - name: Relations
    description: What data is linked to what other data. Allows you to assign authors to articles, products to sales, and whatever other structures you can think of.
    x-collection: directus_relations
  - name: Files
    description: Files can be saved in any given location. Directus has a powerful assets endpoint that can be used to generate thumbnails for images on the fly.
    x-collection: directus_files
  - name: Fields
    description: Fields are individual pieces of content within an item. They are mapped to columns in the database.
    x-collection: directus_fields
  - name: Operations
    description: Operations are the building blocks within Data Flows.
    x-collection: directus_operations
  - name: Versions
    description: Enables users to create unpublished copies of an item, modify them independently from the main version, and promote them to become the new main version when ready.
    x-collection: directus_versions
  - name: Revisions
    description: Revisions are individual changes to items made. Directus keeps track of changes made, so you're able to revert to a previous state at will.
    x-collection: directus_revisions
  - name: Users
    description: Users are what gives you access to the data.
    x-collection: directus_users
  - name: Extensions
    description: Directus can easily be extended through the addition of several types of extensions, including layouts, interfaces, and modules.
    x-collection: directus_extensions
  - name: Activity
    description: All events that happen within Directus are tracked and stored in the activities collection. This gives you full accountability over everything that happens.
    x-collection: directus_activity
  - name: Webhooks
    description: Webhooks.
    x-collection: directus_webhooks
  - name: Settings
    description: Settings control the way the platform works and acts.
    x-collection: directus_settings
  - name: Permissions
    description: Permissions control who has access to what and when.
    x-collection: directus_permissions
  - name: Collections
    description: Collections are the individual collections of items, similar to tables in a database. Changes to collections will alter the schema of the database.
    x-collection: directus_collections
  - name: Flows
    description: Flows enable custom, event-driven data processing and task automation.
    x-collection: directus_flows
  - name: Presets
    description: Presets hold the preferences of individual users of the platform. This allows Directus to show and maintain custom item listings for users of the app.
    x-collection: directus_presets
  - name: Roles
    description: Roles are groups of users that share permissions.
    x-collection: directus_roles

