name: App Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: app-lint-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  app-lint:
    name: App Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run Linter
        run: pnpm eslint:lint
        env:
          NUXT_PUBLIC_PRODUCT_DIRECTUS_URL: https://product-team.directus.app
